version: '3.7'

networks:
  redeinterna:
    driver:
      bridge

services:
  nginx:
    container_name: "node_nginx"
    image: "nginx:1.21"
    user: root
    working_dir: /app/
    volumes:
    #  - ./:/app/
       - ./html:/usr/share/nginx/html
       - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 5000
      - 80
    ports:
      - 5000:5000
      - 80:80
    networks:
      - redeinterna
    depends_on:
      - nginx1

  nginx1:
    image: "nginx:1.21"
    networks:
      - redeinterna
    volumes:
    #  - ./:/app/
       - ./html1:/usr/share/nginx/html


  nginx2:
    image: "nginx:1.21"
    networks:
      - redeinterna
    volumes:
       - ./html2:/usr/share/nginx/html

  nginx3:
    image: "nginx:1.21"
    networks:
      - redeinterna
    volumes:
       - ./html3:/usr/share/nginx/html

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false